# Generated by Django 4.0.4 on 2022-06-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rn', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mark', models.FloatField()),
                ('mail', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
