# Generated by Django 4.0.5 on 2022-06-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=30)),
                ('mob', models.IntegerField()),
                ('product', models.CharField(max_length=30)),
            ],
        ),
    ]
