# Generated by Django 4.0.5 on 2022-06-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_apk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
